meta_product_name: "Me & Arts"
meta_title: "Me & Arts - empower your music"
meta_description: "Bid and listen"
meta_image: "Me-and-arts.png" # should exist in `app/assets/images/`
twitter_account: "@painapol"   # required for Twitter Cards
